/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SongDTO } from "./songDTO";
import type { UserSummaryDTO } from "./userSummaryDTO";

export interface PlaylistDetailDTO {
  id?: number;
  name?: string;
  color?: string;
  songs?: SongDTO[];
  users?: UserSummaryDTO[];
}
