/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SongDTOSongTag } from "./songDTOSongTag";
import type { SongDTOCountry } from "./songDTOCountry";
import type { UserSummaryDTO } from "./userSummaryDTO";

export interface SongDTO {
  id?: number;
  artist?: string;
  title?: string;
  releaseYear?: number;
  youtubeId?: string;
  gradientColor1?: string;
  gradientColor2?: string;
  songTag?: SongDTOSongTag;
  country?: SongDTOCountry;
  addedBy?: UserSummaryDTO;
}
