/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SongMetadataResponse {
  title?: string;
  artist?: string;
  release_year?: number;
  gradient_color1?: string;
  gradient_color2?: string;
}
