/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateSongRequestSongTag } from './updateSongRequestSongTag';
import type { UpdateSongRequestCountry } from './updateSongRequestCountry';

export interface UpdateSongRequest {
  artist?: string;
  title?: string;
  releaseYear?: number;
  youtubeId?: string;
  gradientColor1?: string;
  gradientColor2?: string;
  songTag?: UpdateSongRequestSongTag;
  country?: UpdateSongRequestCountry;
}
