/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateSongRequestCountry = typeof UpdateSongRequestCountry[keyof typeof UpdateSongRequestCountry];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSongRequestCountry = {
  NONE: 'NONE',
  RO: 'RO',
  GB: 'GB',
} as const;
