/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaylistSummaryDTO } from "./playlistSummaryDTO";

export interface UserDetailDTO {
  id?: number;
  username?: string;
  email?: string;
  provider?: string;
  playlists?: PlaylistSummaryDTO[];
}
