/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Generate info PDF for playlist songs
 */
export const exportPlaylistParams = zod.object({
  "playlistId": zod.number()
})

/**
 * @summary Generate PDF for playlist songs
 */
export const exportPlaylistQrParams = zod.object({
  "playlistId": zod.number()
})

/**
 * @summary Generate QR PDF for playlist songs
 */
export const exportPlaylistInfoParams = zod.object({
  "playlistId": zod.number()
})

