/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Join an existing playlist
 */
export const joinPlaylistParams = zod.object({
  "playlistId": zod.number()
})

/**
 * @summary Leave playlist
 */
export const leavePlaylistParams = zod.object({
  "playlistId": zod.number()
})

/**
 * @summary Update current user information
 */
export const updateUserBodyUsernameMin = 3;
export const updateUserBodyUsernameMax = 20;



export const updateUserBody = zod.object({
  "username": zod.string().min(updateUserBodyUsernameMin).max(updateUserBodyUsernameMax).optional(),
  "email": zod.email().optional()
})

/**
 * @summary Get user information by ID
 */
export const getUserParams = zod.object({
  "userId": zod.number()
})

