/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Fetch song metadata from a YouTube URL
 */
export const getSongMetadataQueryParams = zod.object({
  "youtubeUrl": zod.string()
})

