/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Add a new song to the playlist
 */
export const createSongParams = zod.object({
  "playlistId": zod.number()
})








export const createSongBody = zod.object({
  "artist": zod.string().min(1),
  "title": zod.string().min(1),
  "releaseYear": zod.number().optional(),
  "youtubeId": zod.string().min(1),
  "gradientColor1": zod.string().min(1),
  "gradientColor2": zod.string().min(1),
  "songTag": zod.enum(['NONE', 'PLAYLIST', 'SPECIAL', 'ANIME']).optional(),
  "country": zod.enum(['NONE', 'RO', 'GB']).optional()
})

/**
 * @summary Get playlist information
 */
export const getPlaylistParams = zod.object({
  "playlistId": zod.number()
})

/**
 * @summary Update playlist information
 */
export const updatePlaylistParams = zod.object({
  "playlistId": zod.number()
})

export const updatePlaylistBody = zod.object({
  "name": zod.string().optional(),
  "color": zod.string().optional()
})

/**
 * @summary Get information about a particular song in the playlist
 */
export const getSongParams = zod.object({
  "playlistId": zod.number(),
  "songId": zod.number()
})

/**
 * @summary Delete song from the playlist
 */
export const deleteSongParams = zod.object({
  "playlistId": zod.number(),
  "songId": zod.number()
})

/**
 * @summary Edit information about a particular song in the playlist
 */
export const updateSongParams = zod.object({
  "playlistId": zod.number(),
  "songId": zod.number()
})

export const updateSongBody = zod.object({
  "artist": zod.string().optional(),
  "title": zod.string().optional(),
  "releaseYear": zod.number().optional(),
  "youtubeId": zod.string().optional(),
  "gradientColor1": zod.string().optional(),
  "gradientColor2": zod.string().optional(),
  "songTag": zod.enum(['NONE', 'PLAYLIST', 'SPECIAL', 'ANIME']).optional(),
  "country": zod.enum(['NONE', 'RO', 'GB']).optional()
})

