/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateSongRequestCountry = typeof CreateSongRequestCountry[keyof typeof CreateSongRequestCountry];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSongRequestCountry = {
  NONE: 'NONE',
  RO: 'RO',
} as const;
