/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PlaylistSummaryDTO {
  id: number;
  name: string;
  color: string;
  songCount: number;
}
