/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SongDTOSongTag = typeof SongDTOSongTag[keyof typeof SongDTOSongTag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SongDTOSongTag = {
  NONE: 'NONE',
  PLAYLIST: 'PLAYLIST',
  SPECIAL: 'SPECIAL',
  ANIME: 'ANIME',
} as const;
