/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';


/**
 * @summary Register a new user
 */
export const registerBodyUsernameMin = 3;
export const registerBodyUsernameMax = 20;


export const registerBodyPasswordMin = 6;
export const registerBodyPasswordMax = 2147483647;



export const registerBody = zod.object({
  "username": zod.string().min(registerBodyUsernameMin).max(registerBodyUsernameMax),
  "email": zod.email().min(1),
  "password": zod.string().min(registerBodyPasswordMin).max(registerBodyPasswordMax)
})

/**
 * @summary Login with username/email and password
 */




export const loginBody = zod.object({
  "usernameOrEmail": zod.string().min(1),
  "password": zod.string().min(1)
})

